name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "test-implement"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https:///test-implement.herokuapp.com/health"
